### ISSUE TITLE
Sim-workbench: The simulator crashes with json produced from SMK XML

### ISSUE THREAD

**Issue by Sorvalampi** [menu-hanke/sim-workbench#35]
Sim-workbench: The simulator crashes with json produced from SMK XML.

Total nr of stands: 82.

Data and error messages attached.
[Miilukangas_json.txt](https://github.com/menu-hanke/sim-workbench/files/8678978/Miilukangas_json.txt)
[Miilukangas_err.txt](https://github.com/menu-hanke/sim-workbench/files/8678981/Miilukangas_err.txt)

**Comment by jpy-luke** [comment]
This is caused by sapling reference trees with 0.0 diameter crashing the grow_acta function (causing a divide by zero).

A hacky fix (from @Sorvalampi ) is to make alternative branch for grow_acta to grow sapling trees as follows:
if height < 1.3m, increase height by 0.3m. 
If height >= 1.3m and diameter == 0, set diameter to 2 cm, then proceed with existing growth path.

I would rather see this being handled as a pre-processing step. It must be the responsibility of the user to know that grow_acta model does not behave properly with sapling reference trees. So we'll implement (in another task) a pre-processing step to control.yaml, which allows user to filter out sapling trees from the data set.
